respect ignore_errors in grafana_annotations.py
ansible-collections/community.grafana pull request #128
Opened 2020-09-09 17:57 UTC by ko-christ

Respect `ignore_errors: True` task option in `grafana_annotations.py` and don't send an annotation on these tasks.
Also `self.errors += 1` when the error is not ignored otherwise the playbook is marked as failing in `v2_playbook_on_stats` and the execution is marked as red in Grafana.

##### SUMMARY

##### ISSUE TYPE

- Bugfix Pull Request
- Docs Pull Request
- Feature Pull Request
- New Module Pull Request

##### COMPONENT NAME

##### ADDITIONAL INFORMATION

```paste below

```

2020-09-12 13:02 UTC, rrey requested changes

2020-09-12 13:02 UTC, rrey commented on plugins/callback/grafana_annotations.py
> +        if not ignore_errors:
really minor but why not the following to gain a level of indentation ?

```
if ignore_errors:
    return
```

2020-09-12 17:33 UTC, rrey approved these changes

2020-09-15 07:54 UTC, seuf approved these changes

2020-09-15 07:55 UTC, seuf commented
Should be upgrdae the github action `actions/setup-python@v2` instead of `v1` ? the sanity checks fails because of that :(

2020-10-04 16:25 UTC, merged