grafana_team: unable to use spaces or other utf-8 chars in name/title
ansible-collections/community.grafana pull request #169
Opened 2021-04-27 19:09 UTC by CWollinger

##### SUMMARY

grafana_team: unable to use spaces or other utf-8 chars in name/title

Same PR like for grafana_folder #79 

Fix issue #164 

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

grafana_team

##### ANSIBLE VERSION

```paste below
ansible 2.9.15
  config file = /mnt/c/DeveloperArea/Telia/moncap-repo/ansible.cfg
  configured module search path = ['/home/myuser/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.9/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.9.0 (default, Oct  6 2020, 00:00:00) [GCC 10.2.1 20200826 (Red Hat 10.2.1-3)]

collection:
community.grafana 1.2.1
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

Ubuntu 18.04.3 LTS

##### STEPS TO REPRODUCE

Procedure described in : #164

##### EXPECTED RESULTS

Teams should be created.

##### ACTUAL RESULTS

Error, because not URL quote for the get_folder API query.

```paste below
msg": "Grafana Folders API answered with HTTP -1"
```

2021-04-27 19:36 UTC, rrey requested changes
Hi @CWollinger !
Patch is ok but could you update the changelog fragment for 1.1.2 ?
See this PR for info : https://github.com/ansible-collections/community.grafana/pull/166

let me know if you need help

2021-04-27 19:47 UTC, CWollinger commented
Hey @rrey 

I added 2 lines to the 1.2.2.yml file. Hope this is ok...

It is possible to rebase because of the PR conflict?

2021-04-27 21:00 UTC, rrey commented
Yes you have to rebase !

2021-04-28 06:32 UTC, rrey approved these changes

2021-04-28 06:34 UTC, rrey commented
@CWollinger I try to avoid merge commits to have a clean linear history, could you rebase your branch without merge commit ?

2021-04-28 23:07 UTC, seuf approved these changes

2021-04-28 23:08 UTC, merged