add Quickwit datasource
ansible-collections/community.grafana pull request #308
Opened 2023-07-05 16:16 UTC by hoangphuocbk

##### SUMMARY

Add support Quickwit datasource

- Feature Pull Request

##### COMPONENT NAME
datasource

##### ADDITIONAL INFORMATION
https://github.com/quickwit-oss/quickwit-datasource

Example usage

```paste below
- name: Create Quickwit datasource
  community.grafana.grafana_datasource::
    name: "Quickwit"
    grafana_url: "{{ grafana_url }}"
    grafana_user: "{{ grafana_username }}"
    grafana_password: "{{ grafana_password }}"
    access: proxy
    org_id: '1'
    ds_type: quickwit-quickwit-datasource
    ds_url: http://localhost:7280/api/v1
    additional_json_data:
      index: 'hdfs-logs'
      timeField: timestamp
      timeOutputFormat: unix_timestamp_secs
      logMessageField: body
      logLevelField: severity_text
```

2023-10-23 08:15 UTC, seuf approved these changes

2023-10-23 08:19 UTC, seuf commented
Hello @hoangphuocbk . Thanks for your MR. Can you add a changelog fragment please ?

2023-10-24 13:12 UTC, hoangphuocbk commented
@seuf, I added change log as your comment

2023-10-24 13:16 UTC, seuf approved these changes

2024-01-02 10:53 UTC, Nemental approved these changes

2024-01-02 12:06 UTC, Nemental requested changes

2024-01-02 12:06 UTC, Nemental commented on tests/integration/targets/grafana_datasource/tasks/quickwit.yml
> +  grafana_datasource:
```suggestion
  community.grafana.grafana_datasource:
```

2024-01-02 12:06 UTC, Nemental commented on tests/integration/targets/grafana_datasource/tasks/quickwit.yml
> +  grafana_datasource:
```suggestion
  community.grafana.grafana_datasource:
```

2024-01-02 12:06 UTC, Nemental commented on tests/integration/targets/grafana_datasource/tasks/quickwit.yml
> +  grafana_datasource:
```suggestion
  community.grafana.grafana_datasource:
```

2024-01-02 12:06 UTC, Nemental commented on tests/integration/targets/grafana_datasource/tasks/quickwit.yml
> +  grafana_datasource:
```suggestion
  community.grafana.grafana_datasource:
```

2024-01-02 12:06 UTC, Nemental commented on tests/integration/targets/grafana_datasource/tasks/quickwit.yml
> +  grafana_datasource:
```suggestion
  community.grafana.grafana_datasource:
```

2024-01-04 13:24 UTC, merged