docs(grafana_datasource): add influxdb flux example
ansible-collections/community.grafana pull request #353
Opened 2024-04-04 20:28 UTC by nutgood

##### SUMMARY
I've added an example to grafana_datasource to add the flux version of influxdb programatically. It's very hard to find documentation online, especially for people new to ansible (and grafana).

##### ISSUE TYPE
- Docs Pull Request

##### COMPONENT NAME
grafana_datasource

2024-04-05 08:00 UTC, Nemental approved these changes
lgtm, thank you!

2024-04-05 08:01 UTC, Nemental requested changes
Can you please add a changelog fragment please?

2024-04-05 13:19 UTC, nutgood commented
Done @Nemental :)

2024-04-05 13:21 UTC, Nemental requested changes

2024-04-05 13:21 UTC, Nemental commented on changelogs/fragments/353-docs-add-influxdb-flux-example.yml
> +minor_changes:
```suggestion
trivial:
```
I would prefer trivial, because it's not an user affecting change.

2024-04-05 13:28 UTC, Nemental approved these changes
Great, everything is fine - thank you!

2024-04-15 06:26 UTC, rndmh3ro approved these changes

2024-04-15 06:26 UTC, merged